// <auto-generated />
namespace PetGroomingApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Usersfirstlastnameanothertry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usersfirstlastnameanothertry));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121810286_Users-first-last-name-another try"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
