// <auto-generated />
namespace PetGroomingApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class useraddfirstname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useraddfirstname));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121857403_user- add first name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
